@startuml WFCAD
title WFCAD
package View{
    Interface ICanvasView
    class CanvasForm
    ICanvasView  <|..  CanvasForm
}
Package Controller{
    Interface ICanvasController
    class CanvasController
    ICanvasController  <|..  CanvasController
}
Package Model{
    interface ICanvas
    class Canvas
    interface IShape
    abstract class Shape
    class Shape1D
    class Shape2D
    class Line
    class Ellipse
    class Rectangle
    Interface IFramePoint
    class FramePoint
    interface ISnapshot
    class Snapshot
    interface ISnapshots
    class Snapshots
    ICanvas  <|..  Canvas
    IShape  <|..  Shape
    Shape <|-- Shape1D
    Shape <|-- Shape2D
    Shape1D <|-- Line
    Shape2D <|-- Ellipse
    Shape2D <|-- Rectangle
    IFramePoint <|.. FramePoint
    ISnapshot <|.. Snapshot
    ISnapshots <|.. Snapshots
    Canvas --> IShape
    ISnapshot --o Snapshots
    Snapshot --> ICanvas
    IShape --> IFramePoint

}
CanvasForm ..> ICanvasController
CanvasForm --> Shape
CanvasController ..> ICanvas
CanvasController ..> ICanvasView
CanvasController ..> ISnapshots

@enduml